// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function normalizeSupabaseUrl(rawUrl: string) {
  const trimmedUrl = rawUrl.trim().replace(/\/+$/, '');
  const parsedUrl = new URL(trimmedUrl);

  if (parsedUrl.pathname === '/rest/v1' || parsedUrl.pathname === '/auth/v1') {
    return parsedUrl.origin;
  }

  return trimmedUrl;
}

function createSupabaseClient() {
  const rawSupabaseUrl =
    import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL;
  const supabasePublishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY;
  const hasUrl = !!rawSupabaseUrl?.trim();
  const hasPublishableKey = !!supabasePublishableKey?.trim();

  if (import.meta.env.DEV) {
    console.info('[Supabase] public env status', { hasUrl, hasPublishableKey });
  }

  if (!hasUrl || !hasPublishableKey) {
    const missing = [
      ...(!hasUrl ? ['VITE_SUPABASE_URL'] : []),
      ...(!hasPublishableKey ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase public environment variable(s): ${missing.join(', ')}. Google OAuth cannot start without a Supabase URL and publishable key.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const supabaseUrl = normalizeSupabaseUrl(rawSupabaseUrl);

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

